#
# Programmer:    Craig Stuart Sapp <craig@ccrma.stanford.edu>
# Creation Date: Sun Jan 25 05:59:18 PST 2015
# Last Modified: Sun Jan 25 05:59:20 PST 2015
# Filename:      doc/Makefile
# Syntax:        GNU Makefile
#
# Description:   Fill in short descriptions of functions in index.
#


all:
	./insertDescriptions index.md methods > temp.md
	mv temp.md index.md

